matrix:
  - name: Markdown
    sources:
      - "docs/**/*.md"
      - "snippets/**/*.md"
    aspell:
      lang: en
      d: en_US

    dictionary:
      wordlists:
        - wordlist.txt
      output: wordlist.dic
      encoding: utf-8

    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.fenced_code:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
      - pyspelling.filters.url:
