matrix:
  - name: Markdown
    aspell:
      lang: en
      d: en_US

    dictionary:
      wordlists:
        - .github/config/wordlist.txt
      output: .github/config/wordlist.dic
      encoding: utf-8

    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.fenced_code:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
      - pyspelling.filters.url:
